###
POST http://localhost:4000/api/v1/register
Content-Type: application/json

{
    "username": "admin400", 
    "password": "admin400",
    "confPassword":"admin400",
    "role" : "admin"
}


//login admin
###
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "username": "admin300",
    "password": "admin300"
}

//login user
###
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "username": "kakaje",
    "password": "kakaje123"
}



###

DELETE  http://localhost:4000/api/v1/users/7bfc4303-ddf7-4b3b-ae0d-956487934a00
